app/controllers/MoviesController.php
<?php


/**
 * @todo: set page titles and breadcrumbs
 */

class MoviesController extends FrontController
{
    public function filters()
    {
        return array(
            'postOnly + delete rate',
            'accessControl',
        );
    }

    public function actionIndex($page = 1)
    {
        if (Yii::app()->getRequest()->getRequestUri() === '/') {
            $this->redirect(['movies/index']);
        }

        $query = array('sort_by' => 'popularity.desc');

        if (Yii::app()->getRequest()->getParam('filter_newest')) {
            /**
             * There we must define period [from and to],
             * if we not define date to, you can see films that will
             * showing at 2020y.
             */
            $query['release_date.gte'] = (new DateTime())->sub(new DateInterval('P2M'))->format('Y-m-d');
            $query['release_date.lte'] = (new DateTime())->add(new DateInterval('P1W'))->format('Y-m-d');
            $query['sort_by'] = 'release_date.desc';
        }

        $provider = MovieManager::getProvider($query, $page);

        $this->render('index', array(
            'dataProvider' => $provider
        ));
    }

    public function actionView($id)
    {
        $movie = MovieManager::getMovie($id);
        $this->render('view', array(
            'movie' => $movie
        ));
    }

    public function actionEdit($id)
    {
        $model = Movie::model()->findByPk(intval($id));

        if (isset($_POST['Movie'])) {
            $model->attributes = $_POST['Movie'];
            $model->poster_file = CUploadedFile::getInstance($model, 'poster_file');
            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->external_id));
            }
        }

        $this->render('edit', array('model' => $model));
    }

    public function actionDelete()
    {
        $model = $this->loadModel(Yii::app()->getRequest()->getParam('id'));
        $model->delete();
        $this->redirect(array('control'));
    }
    
    public function actionControl()
    {
        $dataProvider = Movie::model()->search();
        $this->render('control', array(
            'dataProvider' => $dataProvider
        ));
    }

    public function actionRate()
    {
        $this->layout = false;
        $id = Yii::app()->getRequest()->getPost('id');
        $rating = Yii::app()->getRequest()->getPost('rating');

        if (MovieManager::setRating($id, $rating)) {
            $this->renderJSON(array('status' => 'ok'));
        } else {
            throw new CHttpException(400);
        }
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Movie the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = Movie::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }
}

app/views/movies/control.php
<?php

/**
 * @var $dataProvider CDataProvider
 */

$dateFormat = Yii::app()->getLocale()->getDateFormat('medium');
$this->widget('zii.widgets.grid.CGridView', array(
    'columns' => array(
        array(
            'name' => 'id',
            'headerHtmlOptions' => array('width' => '100'),
            'htmlOptions' => array('class' => 'text-center')
        ),
        array('name' => 'title'),
        array(
            'headerHtmlOptions' => array('width' => '100'),
            'htmlOptions' => array('class' => 'text-center'),
            'name' => 'release_date',
            'value' => sprintf('Yii::app()->getDateFormatter()->format("%s", $data->release_date)', $dateFormat)
        ),
        array(
            'class' => 'CButtonColumn',
            'htmlOptions' => array('class' => 'text-center'),
            'template' => '{update} {delete}',
            'updateButtonUrl' => 'Yii::app()->controller->createUrl("edit",array("id"=>$data->primaryKey))'
        )
    ),
    'dataProvider' => $dataProvider,
    'ajaxUpdate' => false
));

app/views/movies/edit.php
<?php
/* @var $model Movie */
/* @var $form CActiveForm */
?>

<div class="form">

    <?php $form = $this->beginWidget('CActiveForm', array(
        'id' => 'movie-form',
        'enableAjaxValidation' => false,
        'htmlOptions' => array(
            'class' => 'pure-form',
            'enctype' => 'multipart/form-data'
        )
    )); ?>

    <p class="note">Fields with <span class="required">*</span> are required.</p>

    <?php echo $form->errorSummary($model); ?>

    <div class="row">
        <?php echo $form->labelEx($model, 'external_id'); ?>
        <?php echo $form->textField($model, 'external_id', array('readonly' => true)); ?>
        <?php echo $form->error($model, 'external_id'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'title'); ?>
        <?php echo $form->textField($model, 'title', array('size' => 60, 'maxlength' => 255)); ?>
        <?php echo $form->error($model, 'title'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'overview'); ?>
        <?php echo $form->textArea($model, 'overview', array('rows' => 12, 'cols' => 80)); ?>
        <?php echo $form->error($model, 'overview'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'release_date'); ?>
        <?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
            'model' => $model,
            'attribute' => 'release_date',
            'options' => array(
                'showAnim' => 'fold',
                'dateFormat' => 'yy-mm-dd',
            )
        )); ?>
        <?php echo $form->error($model, 'release_date'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'runtime'); ?>
        <?php echo $form->textField($model, 'runtime'); ?>
        <?php echo $form->error($model, 'runtime'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'genres'); ?>
        <?php echo $form->textField($model, 'genres', array('size' => 80)); ?>
        <?php echo $form->error($model, 'genres'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'poster'); ?>
        <?php if ($model->poster): ?>
            <div>
                <?= CHtml::image($model->getPosterPath(), '', array('style' => 'max-width: 200px;')); ?>
            </div>
        <?php endif;?>
        <?php echo $form->fileField($model, 'poster_file'); ?>
        <?php echo $form->error($model, 'poster_file'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'trailer'); ?>
        <?php echo $form->textField($model, 'trailer', array('size' => 80, 'placeholder' => 'Youtube video id')); ?>
        <?php echo $form->error($model, 'trailer'); ?>
    </div>

    <div class="row buttons">
        <?php echo CHtml::submitButton('Save', array('class' => 'pure-button pure-button-primary')); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

app/views/movies/index.php
<?php

/**
 * @var $dataProvider CDataProvider
 */
?>

<ul>
    <li><?= CHtml::link('Newest movies', array('index', 'filter_newest' => 1)); ?></li>
    <li><?= CHtml::link('Default', array('index')); ?></li>
</ul>
<?php

$dateFormat = Yii::app()->getLocale()->getDateFormat('medium');
$this->widget('zii.widgets.grid.CGridView', array(
    'columns' => array(
        array(
            'name' => 'id',
            'headerHtmlOptions' => array('width' => '100'),
            'htmlOptions' => array('class' => 'text-center')
        ),
        array('name' => 'title'),
        array(
            'headerHtmlOptions' => array('width' => '100'),
            'htmlOptions' => array('class' => 'text-center'),
            'name' => 'release_date',
            'value' => sprintf('Yii::app()->getDateFormatter()->format("%s", $data->release_date)', $dateFormat)
        ),
        array(
            'class' => 'CLinkColumn',
            'htmlOptions' => array('class' => 'text-center'),
            'label' => 'View',
            'urlExpression' => 'array("movies/view", "id" => $data->id)'
        )
    ),
    'dataProvider' => $dataProvider,
    'ajaxUpdate' => false
));

app/views/movies/view.php
<?php

/**
 * @var $movie Movie
 */


echo CHtml::link('Edit', array('edit', 'id' => $movie->id));
$rating = CHtml::textField('rating', '', array('placeholder' => 'Values must be a multiple of 0.50')) . '&nbsp;' .
    CHtml::button('Send', array(
        'id' => 'rating-btn',
        'data-external-id' => $movie->external_id
    ));

$this->widget('zii.widgets.CDetailView', array(
    'data' => $movie,
    'attributes' => array(
        'id',
        'external_id',
        'title',
        'overview',
        'release_date',
        'runtime',
        'genres',
        array('value' => $rating, 'label' => 'Rating', 'type' => 'raw'),
        array(
            'name' => 'poster',
            'type' => 'raw',
            'value' => $movie->poster ? CHtml::image($movie->getPosterPath(), '', array('style' => 'max-width: 100%;')) : 'Not set'
            ),
        array('name' => 'trailer', 'type' => 'raw', 'value' =>  $movie->trailer ? CHtml::tag('iframe',
            array(
                'width' => '640',
                'height' => '390',
                'src' => 'http://www.youtube.com/embed/' . $movie->trailer,
                'frameborder' => 0
        ), '') : 'Not set')
    )
));

$cs = Yii::app()->getComponent('clientScript');
$cs->registerCoreScript('jquery');
$cs->registerScriptFile('/js/rating.js', CClientScript::POS_END);