app/controllers/MoviesController.php
<?php


/**
 * @todo: set page titles and breadcrumbs
 */

class MoviesController extends FrontController
{
    public function filters()
    {
        return array(
            'postOnly + delete rate',
            'accessControl',
        );
    }

    public function actionIndex($page = 1)
    {
        if (Yii::app()->getRequest()->getRequestUri() === '/') {
            $this->redirect(['movies/index']);
        }

        $query = array('sort_by' => 'popularity.desc');

        if (Yii::app()->getRequest()->getParam('filter_newest')) {
            /**
             * There we must define period [from and to],
             * if we not define date to, you can see films that will
             * showing at 2020y.
             */
            $query['release_date.gte'] = (new DateTime())->sub(new DateInterval('P2M'))->format('Y-m-d');
            $query['release_date.lte'] = (new DateTime())->add(new DateInterval('P1W'))->format('Y-m-d');
            $query['sort_by'] = 'release_date.desc';
        }

        $provider = MovieManager::getProvider($query, $page);

        $this->render('index', array(
            'dataProvider' => $provider
        ));
    }

    public function actionView($id)
    {
        $movie = MovieManager::getMovie($id);
        $this->render('view', array(
            'movie' => $movie
        ));
    }

    public function actionEdit($id)
    {
        $model = Movie::model()->findByPk(intval($id));

        if (isset($_POST['Movie'])) {
            $model->attributes = $_POST['Movie'];
            $model->poster_file = CUploadedFile::getInstance($model, 'poster_file');
            if ($model->save()) {
                $this->redirect(array('view', 'id' => $model->external_id));
            }
        }

        $this->render('edit', array('model' => $model));
    }

    public function actionDelete()
    {
        $model = $this->loadModel(Yii::app()->getRequest()->getParam('id'));
        $model->delete();
        $this->redirect(array('control'));
    }
    
    public function actionControl()
    {
        $dataProvider = Movie::model()->search();
        $this->render('control', array(
            'dataProvider' => $dataProvider
        ));
    }

    public function actionRate()
    {
        $this->layout = false;
        $id = Yii::app()->getRequest()->getPost('id');
        $rating = Yii::app()->getRequest()->getPost('rating');

        if (MovieManager::setRating($id, $rating)) {
            $this->renderJSON(array('status' => 'ok'));
        } else {
            throw new CHttpException(400);
        }
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Movie the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = Movie::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }
}

app/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
    <div id="content">
        <?php echo $content; ?>
    </div><!-- content -->
<?php $this->endContent(); ?>

app/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
    <div class="span-19">
        <div id="content">
            <?php echo $content; ?>
        </div><!-- content -->
    </div>
    <div class="span-5 last">
        <div id="sidebar">
            <?php
            $this->beginWidget('zii.widgets.CPortlet', array(
                'title' => 'Operations',
            ));
            $this->widget('zii.widgets.CMenu', array(
                'items' => $this->menu,
                'htmlOptions' => array('class' => 'operations'),
            ));
            $this->endWidget();
            ?>
        </div><!-- sidebar -->
    </div>
<?php $this->endContent(); ?>

app/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="language" content="en">

    <!-- blueprint CSS framework -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css"
          media="screen, projection">
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css"
          media="print">
    <!--[if lt IE 8]>
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css"
          media="screen, projection">
    <![endif]-->


    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css">

    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

    <div id="header">
        <div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
    </div>

    <div id="mainmenu">
        <?php
        $isGuest = Yii::app()->user->isGuest;
        $this->widget('zii.widgets.CMenu', array(
            'items' => array(
                array('label' => Yii::t('app', 'Movies'), 'url' => array('movies/index'), 'visible' => !$isGuest),
                array('label' => Yii::t('app', 'Control'), 'url' => array('movies/control'), 'visible' => !$isGuest),
                array('label' => Yii::t('app', 'Login'), 'url' => array('site/login'), 'visible' => $isGuest),
                array('label' => Yii::t('app', 'Logout'), 'url' => array('site/logout'), 'visible' => !$isGuest)
            ),
        )); ?>
    </div>

    <?php if (isset($this->breadcrumbs)): ?>
        <?php $this->widget('zii.widgets.CBreadcrumbs', array(
            'links' => $this->breadcrumbs,
        )); ?>
    <?php endif ?>

    <?php echo $content; ?>

    <div class="clear"></div>

    <div id="footer">
        Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
        All Rights Reserved.<br/>
        <?php echo Yii::powered(); ?>
    </div><!-- footer -->

</div><!-- page -->

</body>
</html>